### ISSUE TITLE
New Version of ADF inside AMS suite are not properly collected

### ISSUE THREAD

**Issue by ijc5167** [jensengrouppsu/chemPackage#2]
As the subject line suggests, there is an error in the collection process for generating mode files. This is due to a discrepancy between the old version of ADF and how things are being built around it and not being updated for the new version of ADF. There is nothing wrong with the files involved in the process except for, again, the discrepancy between the age of the two versions. 

<img width="683" alt="Screen Shot 2021-06-01 at 12 55 36 PM" src="https://user-images.githubusercontent.com/85187010/120362071-aa405780-c2d8-11eb-9ce1-053c57a4701c.png">

**Comment by jbecca** [comment]
Seems like ADF on the cluster uses the AMS version of ADF. We need to either ensure that both versions can work together or make a separate branch or folder for collecting new ADF files that are from AMS calculations.

**Comment by jbecca** [comment]
@ijc5167 Can you please attach the output file to your comment so we can verify for ourselves that this does not work, and then use your file as a way to test implementation?

**Comment by ijc5167** [comment]
Sure. Attached is the .out file in question in text format.

[freq.txt](https://github.com/jensengrouppsu/chemPackage/files/6578341/freq.txt)
